### ISSUE TITLE
Better respect for the --threads parameter

### ISSUE THREAD

**Issue by oneillkza** [koszullab/hicstuff#57] opened 2021-10-22 20:18 UTC
I'm running hicstuff right now on a large server, and set --threads=48. However I'm noticing that it's running two instances of the aligner, each of which are using 48 threads, for 96 in total! This would be very problematic when running in an HPC environment, if I had specified 48 threads to hictools and 48 threads to the workload manager, but hicstuff tried to use double that. 

Better solutions would be to run the alignment sequentially, or to divide the number of CPUs given to the aligner by two.

**Comment by js2264** [comment] 2023-08-24 22:37
Closing after 2 years since it cannot be reproduced. Don't hesitate to reopen to provide more detail.

**Closed by js2264** 2023-08-24 22:37 UTC
Labels: bug
